tests: replace assertRaises() doing a wild catch
Issue
=====
When migrating assertRaise* to pytest.raises, some tests fail due to
unexpected exceptions

ParallelTest::test_execute_parallel_error fails with:

  AssertionError: "^bad$" does not match "Can't pickle <class
  'unittest.mock.MagicMock'>: it's not the same object as
  unittest.mock.MagicMock"

TestMySQL::test_install_db_exception fails with:

  AssertionError: "FAILED (42): some output" does not match "'MySQL'
  object has no attribute 'rootdir'"

Reason
======

Both test uses assertRaises with `msg="bad"` which one could read as
expecting an exception message having the given message. Instead `msg`
is a message displayed when the exception is not raised and the asserts
would thus match any exception raised, including one we were not
expecting. When converting to `pytest.raises(match='bad')` it matches
the message leading to the unexpected errors.

The issue has been introduced when Parallelism got introduced in 2020 by
Ib2dc728980 and for MySQL in 2018 by Iee44910b21.

Fixes
=====

Replace `assertRaises` calls by `assertRaisesRegex` and update tests:

ParallelTest::test_execute_parallel_error

MagicMock() objects are passed to multiprocessing which uses Pickle
under the hood and that can't reduce a MagicMock() leading to the pickle
error (see https://github.com/python/cpython/issues/100090 ). The test
caught that exception and never validated a command failing.

For the intent of testing, introduce a new RaisingCommand which is
initialized with an exception object that is raised whenever execute()
is called.  Use that instead of MagicMock when exercising Parallel.

TestMySQL::test_install_db_exception

rootdir is initialized by _init_rootdir() which is only called on
start(). That led to a missing attribute exception instead of our
internal exception about the failed command.

Replace the other instances of `assertRaises(msg=*)` with
`assertRaisesRegex()` to ensure we match the exception message.

Bug: T436226
Change-Id: I0e0b375ccac218685fd7bb0bdbfaf4404bf18ef4