build: pass CI environment variable to tox envs
We have a few tests asserting lists to be equal and upon failure pytest
would abbreviate them when displaying the assertion error:

  AssertionError: assert ['Python vers...oo Bar v42.1'] \
                      == ['Python vers...re is bugged']
  E At index 2 diff: 'foo-bar --version: Multiline ' \
                  != 'foo-bar --version: Foo Bar v42.1'
  E Use -v to get more diff

We could pass `--verbose` to have the assertion error message expanded,
but that also causes pytests to output one line per test which is a bit
too verbose.

After looking at `pytest` it would shows a verbose diff when it is
running on CI:

  if verbose <= 0 and not running_on_ci():
    return ["Use -v to get more diff"]

As determinated by `CI` or `BUILD_NUMBER` environment variables being
set:

  def running_on_ci() -> bool:
      """Check if we're currently running on a CI system."""
      # Only enable CI mode if one of these env variables is defined and
      # non-empty.
      # Note: review `regendoc` tox env in case this list is changed.
      env_vars = ["CI", "BUILD_NUMBER"]
      return any(os.environ.get(var) for var in env_vars)

Instruct `tox` to pass the `CI` environment variables to all
environments.

Change-Id: I33ef841412299dddff6fed5c94907378134920bb