Require tox v4 and remove skipsdist/use_develop
The testenv section has `usdevelop = True` which imples skipping sdist.

In tox v4, `skipsdist = True` takes precedence over `usedevelop`and
results in the package never being installed even in `check`.

Require tox 4 version via `minversion = 4`. tox v3 will automatically
provision a environment with an upgraded version of tox, based on my
testing that raises:

   ConfigError: envdir must not equal toxinidir

Which is due to `envdir` having multiple settings and lacking an entry
for the special `.tox` environment to install tox v4 within. This set
envdir to `.tox/.pkg` which is the value used by tox v4.

Replace usage of `skipsdist`/`use_develop` which conflicts with each
other in favor of tox v4 setting `package`.

Bug: T346238
Bug: T345695
Depends-On: Ibe0492836e541d75ad84df22bedeb7c4d1bae9b2
Change-Id: I316cefef9d410c25ead3af78439170908a479c69