Fix --shell when SHELL is not set
When running the Quibble container image with `--shell` it fails because
there is no `SHELL` environment variable set:

TypeError: sequence item 0: expected str instance, NoneType found

Fallback to `bash` in this case.

Help is adjusted example:

  $ SHELL=/bin/zsh quibble --help
    --shell  Drop you in CLI as set by $SHELL (current: /bin/zsh)

When SHELL is not set:

  $ (unset SHELL; quibble --help)
    --shell  Drop you in CLI as set by $SHELL (current: bash [SHELL not set])

Bug: T418461
Change-Id: Iecf3e1da8bd3aef84ab0e5163db6403a5b841faf