Env variables must have a string as value
When running webdriver with an external webserver we update the
environment with: 'QUIBBLE_APACHE': 1. For some reason Python 3.7 uses
os.fsencode against environment values which leads to:

  File "/usr/lib/python3.7/subprocess.py", line 1433, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/usr/lib/python3.7/os.py", line 809, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
  TypeError: expected str, bytes or os.PathLike object, not int

That is apparently due to some security concern on Windows:
https://bugs.python.org/issue30730

Change the value to a string.

Change-Id: I87a5497e5825eb68a9f4b790f00c1d3d3c65f471